# 1-Load the diabetes dataset using datasets()

In [3]:
from sklearn import datasets
import numpy as np
diabetes = datasets.load_diabetes()
names=diabetes.feature_names
print(help(datasets.load_diabetes()))
print(names)




Help on Bunch in module sklearn.utils object:

class Bunch(builtins.dict)
 |  Bunch(**kwargs)
 |  
 |  Container object exposing keys as attributes
 |  
 |  Bunch objects are sometimes used as an output for functions and methods.
 |  They extend dictionaries by enabling values to be accessed by key,
 |  `bunch["value_key"]`, or by an attribute, `bunch.value_key`.
 |  
 |  Examples
 |  --------
 |  >>> b = Bunch(a=1, b=2)
 |  >>> b['b']
 |  2
 |  >>> b.b
 |  2
 |  >>> b.a = 3
 |  >>> b['a']
 |  3
 |  >>> b.c = 6
 |  >>> b['c']
 |  6
 |  
 |  Method resolution order:
 |      Bunch
 |      builtins.dict
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __dir__(self)
 |      Default dir() implementation.
 |  
 |  __getattr__(self, key)
 |  
 |  __init__(self, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __setattr__(self, key, value)
 |      Implement setattr(self, name, value).
 |  
 |  __setstate__(self, state)
 |  
 |  ----------

In [16]:
from scipy.stats import pearsonr
import numpy as np
X = diabetes.data
Xarr=np.array(X)
y = diabetes.target
Matrix=[]
l=[]

for i in range(0,len(Xarr)//2):
      ligne=Xarr[i]
      col=Xarr[i+1]
      Matrix.append(np.corrcoef(ligne,col))

#print(Matrix)
R=np.array(Matrix)
print(R)

[[[ 1.         -0.41008995]
  [-0.41008995  1.        ]]

 [[ 1.         -0.14889115]
  [-0.14889115  1.        ]]

 [[ 1.         -0.64652702]
  [-0.64652702  1.        ]]

 [[ 1.         -0.05791715]
  [-0.05791715  1.        ]]

 [[ 1.          0.18706043]
  [ 0.18706043  1.        ]]

 [[ 1.          0.38517505]
  [ 0.38517505  1.        ]]

 [[ 1.          0.30264412]
  [ 0.30264412  1.        ]]

 [[ 1.         -0.07510203]
  [-0.07510203  1.        ]]

 [[ 1.         -0.08244078]
  [-0.08244078  1.        ]]

 [[ 1.         -0.09761017]
  [-0.09761017  1.        ]]

 [[ 1.         -0.49286875]
  [-0.49286875  1.        ]]

 [[ 1.         -0.23555966]
  [-0.23555966  1.        ]]

 [[ 1.         -0.31133204]
  [-0.31133204  1.        ]]

 [[ 1.         -0.21673204]
  [-0.21673204  1.        ]]

 [[ 1.         -0.23460218]
  [-0.23460218  1.        ]]

 [[ 1.         -0.44021067]
  [-0.44021067  1.        ]]

 [[ 1.         -0.60035674]
  [-0.60035674  1.        ]]

 [[ 1.        

In [5]:
import numpy as np
print(np.corrcoef(Xarr[0],Xarr[1]))           

[[ 1.         -0.41008995]
 [-0.41008995  1.        ]]


[132.48690727  87.76487173  89.43656495  78.54062756 117.30815259
  53.96922606 134.89623528  84.77586198 106.38078192  95.01259249
 129.24215874  58.79718581  93.55165592  92.31891291 122.67538885
  78.00217465  96.55143585  82.44283164 100.84427493 111.65630427
  77.98761646 122.8944742  118.03181441 110.04988678 118.01711899
  86.32544282  97.54219549  81.28461131  94.64223841 110.60710933
  86.16678497  92.06492946  86.256546    83.09588717  86.57507738
  99.74670802  77.65379303 104.68831396 133.19604354 114.84088321
  96.16328895  82.24742072  85.05683412 133.84909202 101.0161551
  87.26008707 103.81830969 142.00510273 102.40317905 112.34406219
 106.0034064   92.95500307  77.14963604  93.01314555  95.82211533
 111.73246382 116.77966828 118.62204163 105.71174651 117.70282329
  84.91204118 125.0573631  110.25859641  94.0381433  109.77036293
  98.48856574 122.63258775 130.39633633 143.71150813  72.07007329
  71.11772389  89.91068274 103.20074139 117.52337842 106.31269894
  59.555975